"""Data contracts shared across the pipeline.

The node graph is the hinge of the whole system: DECOMPOSE produces it, SCOUT
enriches it, COMPILE serializes it. Its shape lives in
``prototype/schemas/node_graph.schema.json`` so the same contract can be reused
verbatim by the on-device Flutter client.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any

from jsonschema import Draft7Validator

SCHEMA_PATH = Path(__file__).resolve().parents[1] / "schemas" / "node_graph.schema.json"

_VALIDATOR: Draft7Validator | None = None


def get_validator() -> Draft7Validator:
    """Load and cache the draft-07 validator for the node graph schema."""
    global _VALIDATOR
    if _VALIDATOR is None:
        with SCHEMA_PATH.open(encoding="utf-8") as fh:
            _VALIDATOR = Draft7Validator(json.load(fh))
    return _VALIDATOR


def validate_node_graph(obj: object) -> list[str]:
    """Return a list of human-readable validation errors. Empty list means valid.

    Also enforces node-id uniqueness, which JSON Schema draft-07 cannot express
    for object arrays.
    """
    errors: list[str] = []
    for err in sorted(get_validator().iter_errors(obj), key=lambda e: list(e.path)):
        location = "/".join(str(p) for p in err.path) or "<root>"
        errors.append(f"{location}: {err.message}")

    if isinstance(obj, dict):
        nodes = obj.get("nodes")
        if isinstance(nodes, list):
            seen: set[str] = set()
            for node in nodes:
                if not isinstance(node, dict):
                    continue
                node_id = node.get("id")
                if isinstance(node_id, str):
                    if node_id in seen:
                        errors.append(f"nodes: duplicate node id {node_id!r}")
                    seen.add(node_id)
    return errors


@dataclass(frozen=True)
class Candidate:
    """An open-source repository or library proposed for a single node."""

    name: str
    url: str
    summary: str = ""
    host: str = ""
    published: str = ""
    score: float = 0.0
    selected: bool = False

    @property
    def clone_url(self) -> str:
        """Best-effort git clone URL. Empty string when the source is not a repo root."""
        url = self.url.rstrip("/")
        for host in ("github.com", "gitlab.com", "bitbucket.org"):
            if host in url:
                parts = url.split(host + "/", 1)
                if len(parts) == 2:
                    segments = [s for s in parts[1].split("/") if s]
                    if len(segments) >= 2:
                        return f"https://{host}/{segments[0]}/{segments[1]}.git"
        return ""


@dataclass(frozen=True)
class TrendSignal:
    """A single community datapoint: a Reddit thread, an X post, a discussion."""

    title: str
    url: str
    source: str = ""
    excerpt: str = ""
    published: str = ""


@dataclass
class ScoutedNode:
    """A node graph entry after SCOUT has attached evidence to it."""

    id: str
    category: str
    title: str
    requirement: str
    search_hint: str = ""
    candidates: list[Candidate] = field(default_factory=list)
    trends: list[TrendSignal] = field(default_factory=list)

    @property
    def chosen(self) -> Candidate | None:
        """The selected candidate, defaulting to the top-ranked one."""
        for candidate in self.candidates:
            if candidate.selected:
                return candidate
        return self.candidates[0] if self.candidates else None

    @property
    def rationale(self) -> str:
        """Composed from real evidence rather than generated by the model.

        This is deliberate: a hallucinated justification in context.json would be
        worse than no justification at all.
        """
        chosen = self.chosen
        if chosen is None:
            return f"No vetted candidate found yet for: {self.requirement}"
        basis = [f"satisfies requirement {self.requirement!r}"]
        if chosen.host:
            basis.append(f"sourced from {chosen.host}")
        if self.trends:
            basis.append(f"{len(self.trends)} community signal(s) reviewed")
        return f"Selected {chosen.name} because it " + ", ".join(basis) + "."


@dataclass
class BrainPayload:
    """Everything COMPILE needs to materialize a .devcontext/ directory.

    This is also the exact object that crosses the Office Kit bridge from phone
    to laptop, which is why it is plain JSON-serializable.
    """

    project_name: str
    summary: str
    nodes: list[ScoutedNode]
    constraints: list[str] = field(default_factory=list)
    target_platforms: list[str] = field(default_factory=list)
    source_prompt: str = ""
    generator: str = "devcontext-ai/0.1.0"
    model: str = ""

    @classmethod
    def from_node_graph(
        cls,
        graph: dict[str, Any],
        *,
        source_prompt: str = "",
        model: str = "",
    ) -> "BrainPayload":
        """Build a payload from a validated node graph, before scouting."""
        return cls(
            project_name=str(graph["project_name"]),
            summary=str(graph["summary"]),
            nodes=[
                ScoutedNode(
                    id=str(n["id"]),
                    category=str(n["category"]),
                    title=str(n["title"]),
                    requirement=str(n["requirement"]),
                    search_hint=str(n.get("search_hint", "")),
                )
                for n in graph["nodes"]
            ],
            constraints=[str(c) for c in graph.get("constraints", [])],
            target_platforms=[str(p) for p in graph.get("target_platforms", [])],
            source_prompt=source_prompt,
            model=model,
        )

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "BrainPayload":
        return cls(
            project_name=str(data["project_name"]),
            summary=str(data["summary"]),
            nodes=[
                ScoutedNode(
                    id=str(n["id"]),
                    category=str(n["category"]),
                    title=str(n["title"]),
                    requirement=str(n["requirement"]),
                    search_hint=str(n.get("search_hint", "")),
                    candidates=[Candidate(**c) for c in n.get("candidates", [])],
                    trends=[TrendSignal(**t) for t in n.get("trends", [])],
                )
                for n in data["nodes"]
            ],
            constraints=[str(c) for c in data.get("constraints", [])],
            target_platforms=[str(p) for p in data.get("target_platforms", [])],
            source_prompt=str(data.get("source_prompt", "")),
            generator=str(data.get("generator", "devcontext-ai/0.1.0")),
            model=str(data.get("model", "")),
        )
